# Generated by Django 6.0.1 on 2026-02-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slika', models.ImageField(upload_to='proizvodi/')),
                ('dostupno', models.BooleanField(default=True)),
            ],
        ),
    ]
