# Generated by Django 6.0.1 on 2026-02-03 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proizvod',
            name='dostupno',
        ),
        migrations.AddField(
            model_name='proizvod',
            name='datum_dodavanja',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proizvod',
            name='kategorija',
            field=models.CharField(choices=[('miris', 'Automiris - Dres'), ('oprema', 'Sportska Oprema')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proizvod',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='proizvodi/'),
        ),
    ]
