# Generated by Django 6.0.1 on 2026-02-05 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_proizvod_dostupno_proizvod_datum_dodavanja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proizvod',
            name='kategorija',
            field=models.CharField(choices=[('miris', 'Automiris - Dres'), ('oprema', 'Sportska Oprema'), ('case', 'Gravirane čaše')], max_length=20),
        ),
        migrations.CreateModel(
            name='DodatnaSlika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(upload_to='proizvodi/galerija/')),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dodatne_slike', to='shop.proizvod')),
            ],
        ),
    ]
