# Generated by Django 6.0.1 on 2026-02-05 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_proizvod_kategorija_dodatnaslika'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_kupca', models.EmailField(max_length=254)),
                ('poruka', models.TextField()),
                ('datum_slanja', models.DateTimeField(auto_now_add=True)),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upiti', to='shop.proizvod')),
            ],
            options={
                'verbose_name': 'Upit',
                'verbose_name_plural': 'Upiti kupaca',
            },
        ),
    ]
