# Generated by Django 6.0.1 on 2026-02-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_upit'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontaktUpit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('naslov', models.CharField(max_length=200)),
                ('poruka', models.TextField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kontakt Upit',
                'verbose_name_plural': 'Generalni Kontakt Upiti',
            },
        ),
    ]
